services:
  web:
    build: .
    container_name: django_app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  static_volume:
