# Generated by Django 5.2.8 on 2025-11-20 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_units_course_total_units_remove_quiz_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default='no name provided', max_length=200),
            preserve_default=False,
        ),
    ]
