# Generated by Django 5.2.8 on 2025-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_created_by_quiz_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentunitscore',
            name='quizzes',
            field=models.ManyToManyField(to='api.quiz'),
        ),
    ]
