# Generated by Django 5.2.8 on 2025-11-19 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, help_text='course-id', primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(help_text='course-name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, help_text='school-id', primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(help_text='school-name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(default=uuid.uuid4, help_text='quiz-id', primary_key=True, serialize=False, unique=True)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, help_text='question-id', primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=2000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, help_text='student-id', primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(help_text='student-name', max_length=200)),
                ('grade', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.UUIDField(default=uuid.uuid4, help_text='unit-id', primary_key=True, serialize=False, unique=True)),
                ('unit_score', models.IntegerField(default=0)),
                ('unit_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.unit'),
        ),
    ]
