# Generated by Django 5.2.8 on 2025-11-19 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='course-id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='course-name', max_length=200)),
                ('units', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='question-id', primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='school-id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='school-name', max_length=200)),
                ('email', models.CharField(help_text='school-email', max_length=200, unique=True)),
                ('phone_number', models.CharField(help_text='school-phone-number', max_length=20, unique=True)),
                ('location', models.CharField(help_text='school-location', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='multiple-choice-id', primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='quiz-id', primary_key=True, serialize=False, unique=True)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.quiz'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='student-id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='student-name', max_length=200)),
                ('email', models.CharField(help_text='student-email', max_length=200, null=True, unique=True)),
                ('phone_number', models.CharField(help_text='student-phone-number', max_length=20, null=True, unique=True)),
                ('grade', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='teacher-id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='teacher-name', max_length=200)),
                ('phone_number', models.CharField(help_text='teacher-phone-number', max_length=20, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teacher'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unit-id', primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.unit'),
        ),
    ]
