# Generated by Django 5.2.8 on 2025-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(default='no-email-provided', help_text='school-email', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default='no location provided', help_text='school-location', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(default='no phone number provided', help_text='school-phone-number', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(help_text='student-email', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='student-phone-number', max_length=20, null=True, unique=True),
        ),
    ]
